# Семинар 2

- про Jupyter Notebook: https://devpractice.ru/python-lesson-6-work-in-jupyter-notebook/

## numpy

- документация: http://www.numpy.org/

Библиотека numpy является удобным инструментом для работы с многомерными массивами с возможностью векторизации вычислений. Рассмотрим базовые вещи, которые можно делать с помощью нее.

In [3]:
import numpy as np

In [13]:
a = np.array([1, 2, 4])
a

array([1, 2, 4])

In [4]:
vec = np.array([[1, 2], [3, 4], [5, 6]])

In [5]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
print(vec)

[[1 2]
 [3 4]
 [5 6]]


С чем мы работаем?

In [15]:
vec.dtype

dtype('int32')

In [16]:
type(vec)

numpy.ndarray

Размер массива:

In [17]:
vec.shape

(3, 2)

Число осей:

In [19]:
vec.ndim

2

У некоторых функций бывает параметр `axis`, который позволяет применить эту функцию по разным осям - в данном случае, по строкам или столбцам:

In [24]:
np.sum(vec)

3

In [21]:
np.sum(vec, axis=0)

array([ 9, 12])

In [22]:
np.sum(vec, axis=1)

array([ 3,  7, 11])

In [36]:
vec.max()

6

Транспонируем массив:

In [32]:
vec.T

array([[1, 3, 5],
       [2, 4, 6]])

In [34]:
vec.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

Обратите внимание, что переменная `vec` не поменялась!

In [35]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

Размеры массивов можно менять:

In [37]:
vec.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
vec.reshape(-1, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [39]:
vec.reshape(2, -1)

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
a = np.array([1, 3, 5])
a.shape

(3,)

Индексирование:

In [43]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [42]:
vec[:, 1]

array([2, 4, 6])

In [44]:
vec[2, :]

array([5, 6])

In [46]:
vec[1:3, 0]

array([3, 5])

In [47]:
vec[::2, :]

array([[1, 2],
       [5, 6]])

Булевы массивы:

In [49]:
vec % 2 == 0

array([[False,  True],
       [False,  True],
       [False,  True]])

In [48]:
is_even = vec % 2 == 0
print(is_even)

[[False  True]
 [False  True]
 [False  True]]


In [50]:
np.sum(is_even)

3

Булевы массивы позволяют вытаскивать элементы с True из массива того-же размера

In [52]:
vec[vec % 2 != 0]

array([1, 3, 5])

In [54]:
vec[vec < 4]

array([1, 2, 3])

Иногда бывает полезно создавать специфичные массивы. Массив из нулей:

In [55]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

Массив из единиц:

In [56]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Единичная матрица:

In [60]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

Массивы можно объединять:

In [ ]:
vec

In [61]:
np.hstack((vec, np.zeros(vec.shape)))

array([[1., 2., 0., 0.],
       [3., 4., 0., 0.],
       [5., 6., 0., 0.]])

In [62]:
np.vstack((vec, np.zeros(vec.shape)))

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

И, наконец - арифметические операции!

In [71]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [64]:
vec + 1

array([[2, 3],
       [4, 5],
       [6, 7]])

In [65]:
vec * 2

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [66]:
vec ** 2

array([[ 1,  4],
       [ 9, 16],
       [25, 36]], dtype=int32)

In [67]:
vec + vec ** 2

array([[ 2,  6],
       [12, 20],
       [30, 42]])

In [68]:
vec * vec ** 2

array([[  1,   8],
       [ 27,  64],
       [125, 216]])

In [69]:
np.sin(vec)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ]])

Матричное умножение:

In [4]:
vec @ (vec ** 2)

NameError: name 'vec' is not defined

In [73]:
vec.dot((vec ** 2).T)

array([[  9,  41,  97],
       [ 19,  91, 219],
       [ 29, 141, 341]])

In [5]:
vec @ (vec ** 2).T

NameError: name 'vec' is not defined

In [75]:
(vec ** 2).T

array([[ 1,  9, 25],
       [ 4, 16, 36]], dtype=int32)

Broadcasting:
https://docs.scipy.org/doc/numpy-1.15.0/user/basics.broadcasting.html

In [76]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [77]:
np.arange(3).reshape(3, 1)

array([[0],
       [1],
       [2]])

In [80]:
vec + np.arange(3).reshape(3, 1)

array([[1, 3],
       [3, 5],
       [5, 7]])

Генерация случайных чисел:

In [83]:
np.random.rand(2, 3)

array([[0.70219827, 0.90320616, 0.88138193],
       [0.4057498 , 0.45244662, 0.26707032]])

In [93]:
np.random.seed(1997)
np.random.rand(2, 3)

array([[0.77114815, 0.07475717, 0.52631002],
       [0.97508762, 0.99222565, 0.46513466]])

In [92]:
np.random.randn(3, 2)  

array([[-0.98623118, -1.94292974],
       [ 2.67737895, -1.81307051],
       [ 0.61121357, -0.25845346]])

In [94]:
np.random.normal(2, 1, size=3)

array([3.22661066, 3.96248068, 3.10383384])

In [95]:
np.random.randint(5, 10, size=3)

array([5, 5, 7])

Почему вообще используют `numpy`?

In [98]:
n = 300
A = np.random.rand(n, n)
B = np.random.rand(n, n)

In [102]:
%%time
C = np.zeros((n, n))
for i in range(n):
    for j in range(n):
        for k in range(n):
            C[i, j] += A[i, k] * B[k, j]

Wall time: 18.7 s


In [101]:
%%time
C = A @ B

Wall time: 996 µs


### Задания для самостоятельного решения

1. Развернуть одномерный массив (сделать так, чтобы его элементы шли в обратном порядке).
2. Найти максимальный нечетный элемент в массиве.
3. Замените все нечетные элементы массива на ваше любимое число.
4. Создайте массив первых n нечетных чисел, записанных в порядке убывания. Например, если `n=5`, то ответом будет `array([9, 7, 5, 3, 1])`. *Функции, которые могут пригодиться при решении: `.arange()`*
5. Вычислите самое близкое и самое дальнее числа к данному в рассматриваемом массиве чисел. Например, если на вход поступают массив `array([0, 1, 2, 3, 4])` и число 1.33, то ответом будет `(1, 4)`. _Функции, которые могут пригодиться при решении: `.abs()`, `.argmax()`, `.argmin()`_
6. Вычисляющую первообразную заданного полинома (в качестве константы возьмите ваше любимое число). Например, если на вход поступает массив коэффициентов `array([4, 6, 0, 1])`, что соответствует полиному $4x^3 + 6x^2 + 1$, на выходе получается массив коэффициентов `array([1, 2, 0, 1, -2])`, соответствующий полиному $x^4 + 2x^3 + x - 2$. _Функции, которые могут пригодиться при решении: `.append()`_
7. Пользуясь пунктом 6, посчитайте первую производную для заданного полинома в заданной точке.

In [1]:
# ┌(▼▼メ)┘ └(メ▼▼)┐

In [105]:
#1Развернуть одномерный массив 
#(сделать так, чтобы его элементы шли в обратном порядке).

a = np.array([1, 2, 3])
a = np.flip(a)
a

array([3, 2, 1])

In [106]:
#2
#Найти максимальный нечетный элемент в массиве.

np.max(a[a % 2 != 0])

3

In [110]:
#3
#Замените все нечетные элементы массива на ваше любимое число.

num = 123
b = a.copy()
b[b % 2 != 0] = num
b

array([123,   2, 123])

In [120]:
#4 Создайте массив первых n нечетных чисел, записанных в порядке убывания.
#Например, если n=5, то ответом будет array([9, 7, 5, 3, 1]).
#Функции, которые могут пригодиться при решении: .arange()

def array_of_n(n):
    '''
    return a flipped array of num
    la-la-la-lei
    '''
    return np.flip(np.arange(1, (2 * n), 2))

In [121]:
array_of_n(10)

array([19, 17, 15, 13, 11,  9,  7,  5,  3,  1])

In [122]:
?array_of_n

5. Вычислите самое близкое и самое дальнее числа к данному в рассматриваемом массиве чисел. Например, если на вход поступают массив array([0, 1, 2, 3, 4]) и число 1.33, то ответом будет (1, 4). Функции, которые могут пригодиться при решении: .abs(), .argmax(), .argmin()


In [124]:
def close_farthest(arr, num):
    closest_pos = np.argmin(np.abs(arr - num))
    farthest_pos = np.argmax(np.abs(arr - num))
    return (arr[closest_pos], arr[farthest_pos])

arr = np.array([0, 1, 2, 3, 4])
num = 1.33
close_farthest(arr, num)

(1, 4)

6. Вычисляющую первообразную заданного полинома (в качестве константы возьмите ваше любимое число). Например, если на вход поступает массив коэффициентов array([4, 6, 0, 1]), что соответствует полиному  4𝑥3+6𝑥2+1 , на выходе получается массив коэффициентов array([1, 2, 0, 1, -2]), соответствующий полиному  𝑥4+2𝑥3+𝑥−2 . Функции, которые могут пригодиться при решении: .append()

In [131]:
def antiderivative(arr):
    power = np.flip(np.arange(1, len(arr)+1))
    antider = arr / power
    antider = np.append(antider, 12)
    
    return antider
    

In [135]:
antiderivative(np.array([5, 12, 4, 2]))

7. Пользуясь пунктом 6, посчитайте первую производную для заданного полинома в заданной точке.

In [152]:
def derivative(arr, point):
    power = np.flip(np.arange(0, len(arr)))
    coef = arr * power
    coef = coef[:-1]
    
    stepen = np.flip(np.arange(0, len(coef)))
    point_arr = np.array([point] * len(stepen))
    coeff0 = np.power(np.float64(point_arr), stepen)
    
    y_point = np.sum(coef * coeff0)
    
    return y_point 

derivative(np.array([4, 6, 4, 1]), 4)

244.0